name: M9A

on:
  push:
    paths:
      - "action.yml"
      - ".github/workflows/M9A.yml"

jobs:
  mirrorchyan:
    runs-on: macos-latest
    steps:
      - id: uploading
        uses: MirrorChyan/uploading-action@v1
        with:
          fake_upload: true

          filetype: latest-release
          filename: "M9A-win-x86_64-*.zip"
          pick_files: '["resource", "interface.json"]'
          exclude_files: '["resource/base/model/ocr/**"]'
          mirrorchyan_rid: M9A

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: MaaXYZ
          repo: M9A
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
