name: MAA_Punish

on:
  push:
    paths:
      - "action.yml"
      - ".github/workflows/MAA_Punish.yml"

jobs:
  mirrorchyan:
    runs-on: macos-latest
    steps:
      - id: uploading
        uses: MirrorChyan/uploading-action@dev
        with:
          fake_upload: true

          filetype: latest-release
          filename: "MPA-win-x86_64-MFW*.zip"
          working-directory: bundles/MPA/
          pick_files: '["resource", "interface.json", "custom"]'
          exclude_files: '["*model/ocr/**"]'
          mirrorchyan_rid: MAA_Punish

          owner: overflow65537
          repo: MAA_Punish
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
