name: MaaFramework

on:
  push:
    paths:
      - "action.yml"
      - ".github/workflows/MaaFramework.yml"

jobs:
  mirrorchyan:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os: [win, macos, linux]
        arch: [aarch64, x86_64]

    steps:
      - id: uploading
        uses: MirrorChyan/uploading-action@v1
        with:
          fake_upload: true

          filetype: latest-release
          filename: "MAA-${{ matrix.os }}-${{ matrix.arch }}-*.zip"
          mirrorchyan_rid: MaaFramework

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: MaaXYZ
          repo: MaaFramework
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
